# 일반 컨트롤러 요청 사용
POST localhost:8080/customer/reactive
Content-Type: application/json

{
  "id": 4,
  "name": "reactiveKotlin",
  "telephone" : {
    "countryCode" : "+010",
    "telephoneNumber" : "12345678"
  }
}

###

# 라우터를 활용한 요청 사용
POST localhost:8080/functional/customer/
Content-Type: application/json

{
  "id": 4,
  "name": "reactiveKotlin",
  "telephone" : {
    "countryCode" : "+010",
    "telephoneNumber" : "12345678"
  }
}

###
# 정보 조회
GET localhost:8080/functional/customers/

###
# 예외 핸들링
POST localhost:8080/functional/customer/
Content-Type: application/json

{
  "id": 4
  "name": "reactiveKotlin",
  "telephone" : {
    "countryCode" : "+010",
    "telephoneNumber" : "12345678"
  }
}
